class Dados():
    def __init__(self):
        self.atributos = [
            "Área danificada",
            "Lesão",
            "Histórico de corte",
            "Data",
            "Decadência externa",
            "Manchas",
            "Corpos de frutas",
            "Vagens de frutas",
            "Germinação",
            "Granizo",
            "Descoloração interna",
            "Folha defeituosa",
            "folha suave",
            "Fragmento de folhas",
            "Manchas circulares",
            "Tamanho das manchas",
            "Manchas-margem",
            "Folhas",
            "Alojamento",
            "Crescimento de mofo",
            "Micélio",
            "Crescimento da planta",
            "Suporte para plantas",
            "Precipitado",
            "Raizes",
            "Esclerócio",
            "Semente",
            "Semente descolorida",
            "Tamanho da semente",
            "Semente tmt",
            "Gravidade",
            "Murchando",
            "Tronco",
            "Cancro do caule",
            "Temperatura"
        ]

        self.valores_atributos =  [
            ["?","espalhado", "áreas-baixas", "áreas-superiores", "campo-inteiro" ],
            ["?","dna", "marrom", "marrom-preto-escuro", "meio-queimado"],
            ["?","diferente-1º-ano", "igual-1º-ano", "igual-ultimos-2-anos", "igual-ultimos-7-anos"],
            ["?","abril", "maio", "junho", "julho", "agosto", "setembro", "outubro"],
            ["?","ausente", "firme e seco"],
            ["?","ausente", "colorido", "Marrom-machas-pretas", "dna"],
            ["?","ausente", "presente"],
            ["?","normal", "doente", "recente", "dna"],
            ["?","90-100%", "80-89%", "lt-80%"],
            ["?","sim", "não"],
            ["?","nenhum", "marrom", "preto"],
            ["?","ausente", "presente"],
            ["?","ausente", "superfice-superior", "superfice-inferior"],
            ["?","ausente", "presente"],
            ["?","ausente", "auréola-amarela", "sem-auréola-amarela"],
            ["?","lt-1/8", "gt-1/8", "dna"],
            ["?","w-s-marg", "no-w-s-marg", "dna"],
            ["?","normal", "anormal"],
            ["?","sim", "não"],
            ["?","ausente", "presente"],
            ["?","ausente", "presente"],
            ["?","normal", "anormal"],
            ["?","normal", "é normal"],
            ["?","lt-norm", "normal", "gt-normal"],
            ["?","normal", "apodrecido", "cistos de vesícula"],
            ["?","ausente", "presente"],
            ["?","normal", "anormal"],
            ["?","ausente", "presente"],
            ["?","normal", "it-normal"],
            ["?","ada", "fungicida", "outros"],
            ["?","menor", "meio-severo", "severo"],
            ["?","asente", "presente"],
            ["?","normal", "anormal"],
            ["?","ausente", "abaixo do solo", "Acima do solo", "Acima do segundo"],
            ["?","lt-normal", "normal", "gt-normal"]
        ]

        self.nome_valores =  [
                ["espalhado", "Áreas-baixas", "áreas-superiores", "Campo-Inteiro" ],
                ["dna", "marrom", "marrom-preto-escuro", "meio-queimado"],
                ["diferente-1º-ano", "igual-1º-ano", "igual-ultimos-2-anos", "igual-ultimos-7-anos"],
                ["abril", "maio", "junho", "julho", "agosto", "setembro", "outubro"],
                ["ausente", "firme e seco"],
                ["ausente", "colorido", "marrom-machas-pretas", "dna"],
                ["ausente", "presente"],
                ["normal", "doente", "recente", "dna"],
                ["90-100%", "80-89%", "lt-80%"],
                ["sim", "não"],
                ["nenhum", "marrom", "preto"],
                ["ausente", "presente"],
                ["ausente", "superfice-superior", "Superfice-inferior"],
                ["ausente", "presente"],
                ["ausente", "auréola-amarela", "sem-auréola-amarela"],
                ["lt-1/8", "gt-1/8", "dna"],
                ["w-s-marg", "no-w-s-marg", "dna"],
                ["normal", "anormal"],
                ["sim", "não"],
                ["ausente", "presente"],
                ["ausente", "presente"],
                ["normal", "anormal"],
                ["normal", "é normal"],
                ["lt-norm", "normal", "gt-normal"],
                ["normal", "apodrecido", "cistos de vesícula"],
                ["ausente", "presente"],
                ["normal", "anormal"],
                ["ausente", "presente"],
                ["normal", "it-normal"],
                ["ada", "fungicida", "outros"],
                ["menor", "meio-severo", "severo"],
                ["asente", "presente"],
                ["normal", "anormal"],
                ["ausente", "abaixo do solo", "Acima do solo", "Acima do segundo"],
                ["lt-normal", "normal", "gt-normal"]
            ]

    def get_atributos(self):
        return self.atributos
    
    def get_valores_atributos(self):
        return self.valores_atributos
    
    
